### ISSUE TITLE
is this repo active ? 

### ISSUE THREAD

**Issue by filchristou** [JuliaDynamics/DiscreteEvents.jl#46]
Hello. Thanks for the very nice package. It is my go-to solution for event based simulation. 
However, is this package actively maintained ? 
There are some automated PR pending, that are easy to accept, but after a lot of time still are not merged..

**Comment by itsdfish** [comment]
I was actually going to ask the same thing. I think the package has been abandoned. I agree that minimal maintenance of dependencies would be easy. I thought there was a procedure established on Discourse for these types of situations. Have you aware of a procedure?

**Comment by pbayer** [comment]
Thank you for your trigger. Sorry for the lack of maintenance. I've had other personal and professional commitments for the last 18 months and unfortunately haven't been able to work with Julia. But I will pick it up again in the next few weeks and do the missing work and maybe some more development. Please give me some time.

Thanks also for continuing to use the package.

**Comment by itsdfish** [comment]
@pbayer, I'm glad to see you are doing well and plan to continue maintaining the package. If you ever decide not to maintain the package, I would be willing to take over. Of course, if you want to designate someone else, that would be fine too.

**Comment by hdavid16** [comment]
I'm happy to jump onboard with contributions to the package once development is continued. It would be nice to have a discrete event simulation package in Julia that is actively maintained and works with Revise.jl (unlike ResumableFunctions.jl). SimJulia.jl and ResumableFunctions.jl are pretty much abandoned.

I spoke with George Datseris (dev for Agents.jl) a while back on Slack and he said we could look into bringing DES into the Julia Dynamics community. This could help keep the package alive. What are your thoughts @pbayer ?

**Comment by pbayer** [comment]
I agree fully – as you write – that 

> It would be nice to have a discrete event simulation package in Julia that is actively maintained …

and I would add "… actively developed". As we have seen, this may become difficult if it depends on a single person. So I support any effort to have it maintained and developed by a team of like-minded people who also want to use it.

**Comment by hdavid16** [comment]
@pbayer, great! I'll set up an introduction on Slack with George.

**Comment by pbayer** [comment]
ok, George Datseris agreed that we can move _DiscreteEvents_ into _JuliaDynamics_.
I will update it to support latest Julia and packages and then move it in the next week.

George asks which people he needs to invite to the org in order to give them admin rights after the transfer. Can I suggest @hdavid16, @itsdfish, me? @filchristou, how about you?

Who else wants to contribute if development starts again?

**Comment by hdavid16** [comment]
This is great! You can add me to the org if desired. Another option is to just give me write access to the ported repo so that I can create branches for developing features and fixing bugs and then ultimately you can review and approve the changes. Either option is fine with me. I look forward to the next stages of Discrete Event Simulation in Julia!

**Comment by filchristou** [comment]
Hey. Sure. I would love to be of help for further developing this package. However, I am not super familiar with the internals, so it would be helpful if in the beginning someone with more experience in the package approves any changes coming from my side.
Traditionally, in my institute we developed and have been using [SimLib](https://www.ikr.uni-stuttgart.de/institute/infrastructure/ikr-simlib-object-oriented-simulation-library/). It would be great to eventually see `DiscreteEvents.jl` being endorsed by our institute and thus potentially providing more manpower.

**Comment by pbayer** [comment]
## Update `DiscreteEvents` to `v0.3.5` 
- [x] add `compat` 0.25 for `Distributions` 
- [x] Remove dynamical multi-threading, see #38
- [x] Rewrite `_scale` in `schedule.jl` (broken by Julia 1.7 or 1.8)
- [x] loosen the links to `DiscreteEventsCompanion` in documentation 

### Caveat
There is some inconsistency now in the code base and documentation due to the removal of the multi-threading. This has to be stream-lined out in the next steps.

**Comment by pbayer** [comment]
@JuliaRegistrator register

Release notes `0.3.5`:
- add `compat` 0.25 for ‘Distributions‘, see issue #45  
- Removed dynamical multi-threading, see issue #38
- Rewritten `_scale` in `schedule.jl` (broken by Julia 1.7 or 1.8)

**Comment by pbayer** [comment]
## Move `DiscreteEvents` into `JuliaDynamics`

I asked George Datseris about the necessary steps to do it and suggested @hdavid16 and me as admins. @filchristou and others: we will be happy to receive and integrate your contributions.

**Comment by pbayer** [comment]
`DiscreteEvents` has been moved into `JuliaDynamics`.
It's now https://github.com/JuliaDynamics/DiscreteEvents.jl

There will be next a team discussion about further development of `DiscreteEvents`. 
There we can plan and take the next steps.

Once the team discussion has started, I will close this issue.

Thank you all and George @Datseris.

**Comment by filchristou** [comment]
>There will be next a team discussion about further development of DiscreteEvents
at https://github.com/orgs/JuliaDynamics/teams/discreteevents.

I am not sure if this link is meant to be publicly accessible, but for me it appears broken.

**Comment by pbayer** [comment]
thanks, you are right. So I started a public discussion at #48

**Comment by hdavid16** [comment]
closing as repo has been revived in JuliaDynamics.
